### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by WebTestNinja** [serenity-js/tutorial-journey-planner#1]
Seems like 'where' method of Question class is deprecated. 
I use Question.about('') to fix this. But still its not working..
After npm install and then npm test, i am getting following error:

1) Scenario: Connie looks for the next train - features/saving_time/journey_planner.feature:7
   Step: When Connie wants to travel from Canary Wharf to Waterloo Underground Station at 17:00, avoiding travelling by Bus, National Rail - features/saving_time/journey_planner.feature:10
   Step Definition: node_modules/serenity-js/src/serenity-cucumber/webdriver_synchroniser.ts:47
   Message:
     function timed out after 60000 milliseconds

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
1m00.007s
Cucumber test run has failed.
[10:51:21] I/local - Shutting down selenium standalone server.

**Comment by jan-molak** [comment]
Well spotted, thanks @WebTestNinja!
